---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maxcalculator
  labels:
    app: max-calculator-deploy
  namespace: timeseries-datastore-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maxcalculator
  template:
    metadata:
      labels:
        app: maxcalculator
    spec:
      volumes:
      - name: freeman-nfs
        persistentVolumeClaim:
          claimName: nfs-freeman-01
      containers:
      - name: maxcalculator
        image: codeman8182/timeseries-ds-max-calculator:1.0.0
        volumeMounts:
        - name: freeman-nfs
          mountPath: /db
        envFrom:
        - configMapRef:
            name: timeseries-ds-config
        env:
        - name: DataStoreSettings__ConnectionString
          value: "/db/tsdatastore/timeseries-max.db"
        - name: MessageBusSettings__UserName
          valueFrom:
            secretKeyRef:
              name: timeseries-user-credentials
              key: username
        - name: MessageBusSettings__Password
          valueFrom:
            secretKeyRef:
              name: timeseries-user-credentials
              key: password            
---
apiVersion: v1
kind: Service
metadata:
  name: timeseries-datastore-maxcalculator
  namespace: timeseries-datastore-dev
spec:
  type: ClusterIP
  selector:
    app: maxcalculator
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80