apiVersion: v1
kind: Secret
metadata:
  name: timeseries-user-credentials
  namespace: timeseries-datastore-dev
type: kubernetes.io/basic-auth
stringData:
  username: timeseries
  password: t0p-Secret