---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: timeseries
  namespace: timeseries-datastore-dev
spec:
  tags:
  - management
  - policymaker
  - administrator
  - monitoring
  rabbitmqClusterReference:
    name: timeseries-datastore-messagebroker
  importCredentialsSecret:
    name: timeseries-user-credentials
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: timeseries-user-permission
  namespace: timeseries-datastore-dev
spec:
  vhost: timeseries-datastore-bus
  user: "timeseries"
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: timeseries-datastore-messagebroker